<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIzmCac3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIzmCac3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIzmCac3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIzmCac3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIzmCac3\App_KernelDevDebugContainer([
    'container.build_hash' => 'IzmCac3',
    'container.build_id' => '7c8f5b03',
    'container.build_time' => 1647734005,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIzmCac3');
