<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_v1_usuariolista' => [[], ['_controller' => 'App\\Controller\\Api\\UsuarioController::lista'], [], [['text', '/api/v1/lista']], [], [], []],
    'api_v1_usuariocadastra' => [[], ['_controller' => 'App\\Controller\\Api\\UsuarioController::cadatra'], [], [['text', '/api/v1/cadastra']], [], [], []],
    'web_usuario_index' => [[], ['_controller' => 'App\\Controller\\UsuarioController::index'], [], [['text', '/']], [], [], []],
    'web_usuario_salvar' => [[], ['_controller' => 'App\\Controller\\UsuarioController::salvar'], [], [['text', '/salvar']], [], [], []],
];
